[misc]
no_self_update = true
only = ["custom_commands", "flatpak", "distrobox", "firmware"]
disable = ["self_update", "toolbx", "containers", "helm", "system"]
ignore_failures = ["distrobox", "flatpak", "pixi", "nix", "node", "pip3", "home_manager", "firmware"]
assume_yes = true
no_retry = false

[commands]
"System Upgrade" = "sudo bootc upgrade"
