pixi global install "atuin"
pixi global install "bash-preexec"
pixi global install "bat"
pixi global install "direnv"
pixi global install "dysk"
pixi global install "eza"
pixi global install "fd"
pixi global install "gh"
pixi global install "glab"
pixi global install "rg"
pixi global install "shellcheck"
pixi global install "tealdeer"
pixi global install "television"
pixi global install "trash-cli"
pixi global install "ugrep"
pixi global install "yq"
pixi global install "zoxide"
